# Generated by Django 3.2 on 2021-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_alter_sensorset_ip_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorset',
            name='ip_adress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorset',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sensorset',
            name='plant',
            field=models.CharField(max_length=50),
        ),
    ]
