# Generated by Django 3.2 on 2021-04-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20210414_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='light',
            new_name='li_IR',
        ),
        migrations.AddField(
            model_name='data',
            name='li_UV',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='li_vis',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
