# Generated by Django 3.2 on 2021-04-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_rename_ip_adress_sensorset_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='sens_id',
            new_name='sensorset',
        ),
    ]
