# Generated by Django 3.2 on 2021-04-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
